version: '3.9'

services:
  postgres:
    container_name: apipark_db
    image: postgres:14.5
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - apipark:/var/lib/postgresql/data
    networks:
      - apipark_net
  
  apijava:
    container_name: apipark_dev
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    networks:
      - apipark_net
      
networks:
  apipark_net:
    driver: bridge

volumes:
  apipark:    
